pipeline {

  environment {
    PROJECT_DIR = "/app"
    REGISTRY = "asaleh98/secure_rest_api"
    DOCKER_CREDENTIALS = "docker_auth"
    DOCKER_IMAGE = " "
  }

  agent any

  options {
    skipStagesAfterUnstable()
  }

  stages('cloning the code from git'){
    steps{
      git branch: 'main',
      url: 'https://github.com/Asaleh98/calc_full_infra/tree/main/calc_full_infra'
    }
  }

  stage('Build-Image'){
    steps {
      script {
        DOCKER_IMAGE  docker.build REGISTRY
      }
    }
  }


  stage('Deplot to Docker Hub'){
    steps {
      script{
        docker.withRegistry(' ', DOCKER CREDENTIALS){
          DOCKER_IMAGE.push()
        }
      }
    }
  }

  stage('Removing Docker image'){
    steps{
      sh "docker rmi $REGISTRY"
    }
  }


}
